name: Deploy Fukusuke App to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Sync files to production server
      #   uses: easingthemes/ssh-deploy@v5.1.0
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "."
      #     REMOTE_HOST: "203.142.86.243"
      #     REMOTE_USER: "fki"
      #     REMOTE_PORT: "9090"
      #     TARGET: "/opt/fukusuke-v2"

      - name: Deploy to production server 1
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER_1 }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT_1 }}
          script: |
            cd /opt/fukusuke-v2
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S git pull origin main
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan config:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan route:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan view:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan optimize

      - name: Deploy to production server 2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER_2 }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT_2 }}
          script: |
            cd /opt/fukusuke-v2
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S git pull origin main
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan config:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan route:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan view:cache
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S php artisan optimize
