name: Deploy Fukusuke App to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      # - name: Install dependencies
      #   run: npm install

      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.2'

      # - name: Install Composer
      #   run: composer install --optimize-autoloader --no-dev --no-interaction --no-progress --prefer-dist

      # - name: Sync files to production server
      #   uses: easingthemes/ssh-deploy@v5.1.0
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "."
      #     REMOTE_HOST: "203.142.86.243"
      #     REMOTE_USER: "fki"
      #     REMOTE_PORT: "9090"
      #     TARGET: "/opt/fukusuke-v2"

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: fki2024
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /opt/fukusuke-v2
            echo "$password" | sudo -S git pull origin main
            echo "$password" | sudo -S php artisan config:cache
            echo "$password" | sudo -S php artisan route:cache
            echo "$password" | sudo -S php artisan view:cache
            echo "$password" | sudo -S php artisan optimize
